[package]
name = "day13"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
itertools = "0.14"
nom = "8"
took = "0.1"
once_cell = "1"
